export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const POST_INFO_REQUEST = 'POST_INFO_REQUEST';
export const POST_INFO_SUCCESS = 'POST_INFO_SUCCESS';
export const POST_INFO_FAILURE = 'POST_INFO_FAILURE';

export const EDIT_POST_REQUEST = 'EDIT_POST_INFO_REQUEST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_INFO_SUCCESS';
export const EDIT_POST_FAILURE = 'EDIT_POST_INFO_FAILURE';

export const POST_COMMENTS_REQUEST = 'POST_COMMENTS_REQUEST';
export const POST_COMMENTS_SUCCESS = 'POST_COMMENTS_SUCCESS';
export const POST_COMMENTS_FAILURE = 'POST_COMMENTS_FAILURE';
