export const REMOVE_GOOD = 'REMOVE_GOOD';
export const GET_GOOD_DETAILS = 'GET_GOOD_DETAILS';
export const CHANGE_GOOD_AMOUNT = 'CHANGE_GOOD_AMOUNT';

export const ADD_GOOD_REQUEST = 'ADD_GOOD_REQUEST';
export const ADD_GOOD_SUCCESS = 'ADD_GOOD_SUCCESS';
export const ADD_GOOD_FAILURE = 'ADD_GOOD_FAILURE';

export const FETCH_GOODS_REQUEST = 'FETCH_GOODS_REQUEST';
export const FETCH_GOODS_SUCCESS = 'FETCH_GOODS_SUCCESS';
export const FETCH_GOODS_FAILURE = 'FETCH_GOODS_FAILURE';

export const REMOVE_GOOD_STARTED = 'REMOVE_GOOD_STARTED';
export const REMOVE_GOOD_SUCCESS = 'REMOVE_GOOD_SUCCESS';
export const REMOVE_GOOD_FAILURE = 'REMOVE_GOOD_FAILURE';

export const ADD_GOOD_IN_CART_SUCCESS = 'ADD_GOOD_IN_CART_SUCCESS';

export const FETCH_GOODS_IN_CART_REQUEST = 'FETCH_GOODS_IN_CART_REQUEST';
export const FETCH_GOODS_IN_CART_SUCCESS = 'FETCH_GOODS_IN_CART_SUCCESS';
export const FETCH_GOODS_IN_CART_FAILURE =
  'FETCH_GOODS_IN_CART_REQUEST_FAILURE';

export const CALC_SUM = 'CALC_SUM';
